@startuml "starter-skin"

!define DEFAULT_LEVELS 7
!define DEFAULT_FONT_SIZE 12
!define DEFAULT_FONT_SCALE 2
!define DEFAULT_LINE_THICKNESS 1
!define DEFAULT_LINE_COLOR #333333
!define DEFAULT_SHADOWING 1
!define DEFAULT_MARGIN 25
!define DEFAULT_BGCOLOR LightYellow
!define DEFAULT_FGCOLOR Black

!if (%not(%variable_exists("$BGCOLOR_DEFAULT")))
    !$BGCOLOR_DEFAULT = DEFAULT_BGCOLOR
!endif

!if (%not(%variable_exists("$FGCOLOR_DEFAULT")))
    !$FGCOLOR_DEFAULT = DEFAULT_FGCOLOR
!endif

!DEFAULT_THEME = {
    "colors": [
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" },
        { "fg": "$FGCOLOR_DEFAULT", "bg": "$BGCOLOR_DEFAULT" }
    ]
}

!if (%not(%variable_exists("$THEME")))
    !$THEME = DEFAULT_THEME
!endif

!if (%not(%variable_exists("$LEVELS")))
    !$LEVELS = DEFAULT_LEVELS
!endif

!if (%not(%variable_exists("$FONT_SIZE")))
    !$FONT_SIZE = DEFAULT_FONT_SIZE
!endif

!if (%not(%variable_exists("$FONT_SCALE")))
    !$FONT_SCALE = DEFAULT_FONT_SCALE
!endif

!if (%not(%variable_exists("$BGCOLOR_ROOT")))
    !$BGCOLOR_ROOT = $THEME.colors[0].bg
!endif

!if (%not(%variable_exists("$FGCOLOR_ROOT")))
    !$FGCOLOR_ROOT = $THEME.colors[0].fg
!endif

!if (%not(%variable_exists("$LINE_THICKNESS")))
    !$LINE_THICKNESS = DEFAULT_LINE_THICKNESS
!endif

!if (%not(%variable_exists("$LINE_COLOR")))
    !$LINE_COLOR = DEFAULT_LINE_COLOR
!endif

!if (%not(%variable_exists("$SHADOWING")))
    !$SHADOWING = DEFAULT_SHADOWING
!endif

!if (%not(%variable_exists("$MARGIN")))
    !$MARGIN = DEFAULT_MARGIN
!endif

!procedure arrow_style()
    LineThickness $LINE_THICKNESS
    LineColor $LINE_COLOR
!endprocedure

!procedure root_style()
    BackgroundColor $BGCOLOR_ROOT
    FontColor $FGCOLOR_ROOT
    FontSize $calc_font(0)
!endprocedure

!procedure depth_style($level)
    BackgroundColor $get_background($level)
    FontColor $get_fontcolor($level)
    FontSize $calc_font($level)
!endprocedure

!function $get_background($level)
    !$index = %intval($level)
    !$background = $THEME.colours[$index]
    !return $background
!endfunction

!function $get_fontcolor($level)
    !$index = %intval($level)
    !$color = $THEME.colours[$index].fg
    !return $color
!endfunction

!function $calc_font($level)
    !$scale = %intval($FONT_SCALE)
    !$factor = %intval($LEVELS) - %intval($level)
    !$adjustment = $factor * $scale
    !return %intval($FONT_SIZE) + $adjustment
!endfunction

<style>
mindmapDiagram {
    node {
        Shadowing $SHADOWING
        Margin $MARGIN
    }
    rootNode {
        root_style()
    }
    :depth(1) {
        depth_style(1)
    }
    :depth(2) {
        depth_style(2)
    }
    :depth(3) {
        depth_style(3)
    }
    :depth(4) {
        depth_style(4)
    }
    :depth(5) {
        depth_style(5)
    }
    :depth(6) {
        depth_style(6)
    }
    :depth(7) {
        depth_style(7)
    }
    arrow {
        arrow_style()
    }
}
</style>
@enduml
