@startuml "yellow-theme"
!$custom_config = {
    "levels": [
        { "bgcolor": "LightYellow", "fgcolor": "#333", "fontsize": 16 }
    ],
    "arrow": { "thickness": 1, "color": "#333", "style": 0 },
    "layout": { "padding": 14, "margin": 12, "shadowing": 0, "roundcorner": 20 },
    "leaf": {},
    "boxless": {}
}
@enduml
