@startuml

!$ROOT_BACKGROUND_COLOR = LightYellow
!$DEPTH1_BACKGROUND_COLOR = LightYellow
!$DEPTH2_BACKGROUND_COLOR = LightYellow
!$DEPTH3_BACKGROUND_COLOR = LightYellow
!$LINE_THICKNESS = 1
!$SHADOWING = 0

@enduml
